### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-registry#111]
On the aiidalab registry page, https://aiidalab.github.io/aiidalab-registry/index.html

The footer says

> This page was auto-generated by the [AiiDAlab](https://www.materialscloud.org/aiidalab) application. This [AiiDAlab registry](http://aiidateam.github.io/aiida-registry) page is maintained by the [AiiDAlab](https://www.materialscloud.org/aiidalab) team.

The second link "AiiDAlab registr" actually links to AiiDA plugin registry. I guess that is a mistake? If that is intentionally, it needs to be reworded.

**Comment by yakutovicha** [comment]
> The second link "AiiDAlab registr" actually links to AiiDA plugin registry. I guess that is a mistake? If that is intentionally, it needs to be reworded.

originally the code was taken from the aiida registry, so it is a leftover. I will label it as a bug and put it high in priority to fix.
