### ISSUE TITLE
renaming groups

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-registry#13]
Here comes my proposal:

 - rename "groups" to "categories"
 - add a "categories.json" that contains "description" and "title" fields for each category
 - categories:
   - label: title/description
    - utilities: "Utilities" / Utility apps for everyday tasks
    - configuration: "Configuration" / Apps that configure your AiiDA lab setup.
    - quantum: "Quantum" / Apps that perform quantum-mechanical calculations.
    - classical: "Classical" / Apps that perform calculations based on classical force fields.

Of course, apps can be in more than one category.

@CasperWA @yakutovicha @giovannipizzi Let me know what you think today. 
I will then make the corresponding changes.

P.S. 'configuration' could also be called 'system' (both would be fine with me).

**Comment by CasperWA** [comment]
Looks great!

Why do we need a 'label' category?

Just to understand it completely.
For `categories.json`, you're thinking a schema JSON and something like?:

```json
{
    "Utilities": {
        "description": "Utility apps for everyday tasks"
    },
    ...
}
```

And then change the "groups" key to "categories" in `apps.json`?

**Comment by ltalirz** [comment]
> Why do we need a 'label' category?

This was to give the form of the list that followed ;-)

> Just to understand it completely.

json with 
```json
{
    "utilities": {
       "title: "Utilites",
        "description": "Utility apps for everyday tasks"
    },
    ...
}
```

> Additionally, I think it is a better idea to change "configuration" to "system" or "AiiDA Lab config". 

Ok, then let's go for "system"

**Comment by CasperWA** [comment]
And the reason for not make the keys of the JSON the titles, is for aesthetic reasons?
I guess we could also do:

```json
[
    {
        "title": "Utilities",
        "description": "Utility apps for everyday tasks"
    },
    ...
]

Or perhaps it is easier to use the dict format you propose in order to make an easier coupling with `apps.json`?

**Comment by ltalirz** [comment]
For categories we need both an identifier for apps.json and a title (which might be longer, have spaces etc. for displaying it).
Let's go with the dict format.

**Comment by ltalirz** [comment]
Hm... I've started to make the PR and I feel "system" is not such a useful category after all.
I'm looking for a category that will contain things that set up computers, install apps etc.

I'll go with "setup" for the PR (which is also how these things are called in AiiDA).
Then we can still discuss.
