### ISSUE TITLE
Rename the default branch `master` -> `main`

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-registry#132]
I rename the default branch name from `master` -> `main` to conform with "modern" github convention. 

To update your local branch, run:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

@danielhollas @yakutovicha I case you didn't notice.

**Comment by danielhollas** [comment]
@unkcpz this one can be closed.
