### ISSUE TITLE
update metadata.json of apps

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-registry#14]
We should make sure that every app has at least `version`, `authors` and `state`.

Todo Leopold:
 - [x] https://github.com/aiidateam/aiida_demos.git
 - [x] https://github.com/aiidalab/aiidalab-persistence-homology.git
 - [x] https://github.com/aiidalab/aiidalab-quantum-mobile
 - [x] https://github.com/aiidalab/aiidalab-widgets-base

@CasperWA perhaps we can work on this together

**Comment by CasperWA** [comment]
Todo Casper:

- [ ] [home](https://github.com/aiidalab/aiidalab-home)
- [ ] [aiida](https://github.com/aiidalab/aiidalab-aiida)
- [ ] [cscs](https://github.com/aiidalab/aiidalab-cscs)
- [ ] [epfl-supercomputers](https://github.com/aiidalab/aiidalab-epfl-supercomputers)
- [ ] [empa-surfaces](https://github.com/cpignedoli/aiidalab-empa-surfaces)
- [ ] [empa-reactions](https://github.com/edditler/aiidalab-empa-reactions)
- [ ] [empa-scanning-probe](https://github.com/eimrek/aiidalab-empa-scanning-probe)
- [ ] [units](https://github.com/aiidalab/aiidalab-units)
- [ ] [backup](https://github.com/aiidalab/aiidalab-backup)
- [ ] [manage-structure](https://github.com/aiidalab/aiidalab-manage-structures)
- [ ] [calculation-examples](https://github.com/aiidalab/aiidalab-calculation-examples.git)
- [ ] [epfl-lsmo](https://github.com/yakutovicha/aiidalab-epfl-lsmo.git)
- [ ] [vasp-example](https://github.com/DropD/mc-vasp-example.git)
- [X] [optimade](https://github.com/aiidalab/aiidalab-optimade.git)

**Comment by CasperWA** [comment]
I propose we rename the AiiDA Lab app "aiida" to "aiida-tools", as to have a more apt name for the app.

**Comment by ltalirz** [comment]
Good point to rename "aiida" - what about "aiida-cockpit"?

**Comment by CasperWA** [comment]
> Good point to rename "aiida" - what about "aiida-cockpit"?

Hehe - how grand. I was just echoing the existing title. But sure. We can rename it throughout the app to cockpit.

**Comment by yakutovicha** [comment]
Everything is done here, I believe.
