### ISSUE TITLE
Nicer structure of logo and description for apps

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-registry#18]
As raised by @ltalirz in PR #12, [here](https://github.com/aiidalab/aiidalab-registry/pull/12#issuecomment-470564323), the position of the picture with respect to the text for each app in the index, should be optimized.

An optimization is most definitely welcome for the `singlepage.html` as well.

**Comment by ltalirz** [comment]
Just to clarify, I was talking just about the `singlepage.html` (details page) there.
For me, the index.html is already very nice

**Comment by CasperWA** [comment]
Fixed by #12.
