### ISSUE TITLE
Update GitHub pages deployment through Travis

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-registry#20]
Looking through Travis I found [this](https://docs.travis-ci.com/user/deployment/pages/).

Do you suppose we can simplify the deployment here as well as for the [AiiDA registry](https://github.com/aiidateam/aiida-registry)?

**Comment by ltalirz** [comment]
Looks like it.
The current approach is working fine, though, so unless you really want to play with it I would say this can wait until we encounter issues.

**Comment by CasperWA** [comment]
I was just thinking we could go around the `deploy.sh` file and it's intricacies. But it's not so important as long as it still works, for sure.

**Comment by ltalirz** [comment]
Don't let me stop you from playing with it if you like to :-)
Just try it out in a fork first.

**Comment by CasperWA** [comment]
Right! Got away from it again.
I think I'm done (initially) with playing around with pytest and Travis in #19 :) :+1: 
I plan to add some more tests later, if needed.

**Comment by yakutovicha** [comment]
@CasperWA do we need to keep this issue open, or all the remaining to-do things are listed in #21?

**Comment by CasperWA** [comment]
Closing this and moving further discussions to #21.
