### ISSUE TITLE
Delete mc-vasp-example app?

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-registry#35]
I think the app is dead: the only PR is not merged (from March 2019) and @DropD is not replying to emails. I think we should either drop it from the registry or, maybe, move it under aiidalab organization. The latter can only be done If Rico replies and agrees, of course.

Mentioning @ltalirz, @giovannipizzi for the information. Also mentioning @espenfl in case you would like to take over the development.

**Comment by espenfl** [comment]
@yakutovicha It is dead. Of course we would like to offer such an app from the VASP side, but the current functionality is certainly broken. Question is, is it at this point better to start from scratch than porting the example? What has changed in the interface (example app to AiiDA Lab)? Happy to take over the development, but I guess we would call it something more permanent in that case as well.

**Comment by yakutovicha** [comment]
Thanks @espenfl for the reply

> Question is, is it at this point better to start from scratch than porting the example?
> What has changed in the interface (example app to AiiDA Lab)?

Never looked at that code (and, honestly, don't have time to). But what I know is that this app was essentially done for AiiDA 0.12. And with 99% probability, you want to start development in AiiDA 1.0 directly :). 

Taking into account the renaming we probably don't want to keep this app in the registry. Would you all agree?

**Comment by ltalirz** [comment]
Fine with me
