### ISSUE TITLE
What to do with persistence-homology app?

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-registry#36]
@ltalirz, would you like to update it?

or, otherwise, we can move it to [aiidalab-epfl-lsmo](https://github.com/lsmo-epfl/aiidalab-epfl-lsmo) app and update it there

let me know.

**Comment by ltalirz** [comment]
The first option sounds good to me, thanks!

**Comment by yakutovicha** [comment]
alright, will take care of that.
