### ISSUE TITLE
migration of AiiDA lab applications

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-registry#40]
- [x] aiida cockpit: merge in to aiidalab widgets @yakutovicha 
- [ ] ~~aiida tutorials: @sphuber will decide whether to keep.~~  (@yakutovicha: removed)
- [x] optimade client: @CasperWA
- [x] aiidalab widgets
- [ ] ~~calculation examples: to remove and replace by aiidalab-cp2k~~ (@yakutovicha: removed)
- [ ] ~~cscs: to remove temporarily for update~~ (@yakutovicha: replaced by setup computer/code from awb)
- [ ] ~~epfl: to remove temporarily for update~~ (@yakutovicha: replaced by setup computer/code from awb)
- [x] home
- [x] lsmo apps: to be migrated (removed temporarily) @yakutovicha 
- [x] nanoribbons: @cpignedoli please check when completed
- [x] quantum espresso
- [ ] ~~quantum mobile~~ (@yakutovicha: removed)
- [x] scanning_probe: @eimrek please check when migration completed
- [x] surfaces: @cpignedoli

**Comment by ltalirz** [comment]
Incompatible apps temporarily removed in https://github.com/aiidalab/aiidalab-registry/pull/41

(Check there when re-adding to avoid retyping json)

**Comment by eimrek** [comment]
Thanks for the reminder, Leopold. I finished the migration of the scanning_probe app, everything should now be working with aiida 1.0.

**Comment by yakutovicha** [comment]
I am closing the issue. I doubt that the remaining apps will be migrated.
