### ISSUE TITLE
Remove `version` key from the metadata.json

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-registry#55]
To my knowledge this key is not used anywhere, so can be safely deleted.

**Comment by yakutovicha** [comment]
pinging @csadorf and @CasperWA for the input.

**Comment by CasperWA** [comment]
This may be used in the novel app installation code, but I'm not certain. I guess we're going on git tags there. I'll leave it to @csadorf to put the final nail in this coffin.

**Comment by yakutovicha** [comment]
Yes, to my understanding we are fully relying on Git tags now.

**Comment by CasperWA** [comment]
It's worth considering whether this should still be here for backwards compatibility. But I am not sure it's needed. Again, I'd refer to @csadorf on this point.

**Comment by csadorf** [comment]
Yes, I'd like to remove this key as well. To ensure that this happens in a backwards compatible manner, we will have to formally deprecate it. I can have a look at that.

**Comment by yakutovicha** [comment]
fixed in #59
