### ISSUE TITLE
Duplicate parts for quantum-espresso app

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-registry#88]
https://github.com/aiidalab/aiidalab-registry/blob/78fbf6274a97bbd303b025d102ffe2e1a51b8f4e/apps.yaml#L44-L46

Here we have two duplicate registry infomation for quantum-espresso. I think it is problematic, correct? 
Besides, if I understand correctly, the `apps,yaml` file is only for registering an app but the standard way to set the detailed metadata is for every app they define metadata in `setup.cfg` and aiidalab-registry will fetch them, and update the database. 

So in principle, `apps.yaml` file only need the app name and field `releases` defined. The reason we have to keep `apps.yaml` as it is now is that not all apps using standard `setup.cfg` to format to set metadata. Am I correct? If so, we can create PRs for those apps or ask them to update the app compatible with the standard metadata definition. 

Pinning @csadorf @yakutovicha for comment.

**Comment by csadorf** [comment]
> https://github.com/aiidalab/aiidalab-registry/blob/78fbf6274a97bbd303b025d102ffe2e1a51b8f4e/apps.yaml#L44-L46
> 
> Here we have two duplicate registry infomation for quantum-espresso. I think it is problematic, correct? 

No, the releases are sourced from both release lines, this is a well-supported and intended way of defining releases. In this case we use this mechanism to override requirements for the older releases. One could potentially remove some ambiguity by ensuring that the release lines don't overlap.

> Besides, if I understand correctly, the `apps,yaml` file is only for registering an app but the standard way to set the detailed metadata is for every app they define metadata in `setup.cfg` and aiidalab-registry will fetch them, and update the database.

> So in principle, `apps.yaml` file only need the app name and field `releases` defined. The reason we have to keep `apps.yaml` as it is now is that not all apps using standard `setup.cfg` to format to set metadata. Am I correct?

Yes, the metadata in the registry is for backwards compatibility.

> If so, we can create PRs for those apps or ask them to update the app compatible with the standard metadata definition.
> 
> Pinning @csadorf @yakutovicha for comment.

Yes, that would be good.

**Comment by unkcpz** [comment]
closed by #90
